### ISSUE TITLE
No response after install

### ISSUE THREAD

**Issue by Michaelwucoc** [eofitg/Hypixel-Query-Robot#1]
Can you give me a lua.json file. It dont have any response after i intsall

**Comment by eofitg** [comment]
Hypixel has changed their API fetch method since last update, and now everything in this project may be outdated~~(that I've almost abandoned it)~~. I'm sorry I can't be of any help either.

**Comment by eofitg** [comment]
Hypixel has changed their API fetch method since last update, and now everything in this project may be outdated(and I've almost abandoned it). I'm sorry I can't be of any help either.
